name: news_application
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  provider: ^6.0.5
  google_fonts: ^4.0.3
  flutter_localization: ^0.1.14
  flutter_locales: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/locales/
    - assets/locales/en.json
    - assets/locales/ar.json

flutter_intl:
  enabled: true


